    - name: installing nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: copying nginx configuration file
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: importing common role - App prerequisites  for frontned
      ansible.builtin.import_role:
        name: common
        tasks_from: appprequsites
      vars:
        app_dir: /usr/share/nginx/html
        component: frontend

    - name: starting nginx service
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes

