- name: remove nginx directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
- name: create nginx directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
- name: download and extract front-end application code
  ansible.builtin.unarchive:
    src:  https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: "{{ app_dir }}"
    remote_src: yes